version: '3.0'
services:
  rasa:
    build: ./rasa
    ports:
      - 5005:5005
    volumes:
      - ./rasa:/app
    command:
      - run

  app:
    restart: always
    build: ./rasa/actions
    expose:
      - "5055"
    ports:
      - "5055:5055"
    volumes:
      - ./rasa/actions:/app/actions
