version: '3.0'
services:
  rasa:
    build: ./
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run

  app:
    restart: always
    # image: "rasa/rasa-x-demo:${RASA_X_DEMO_VERSION}"
    build: ./actions
    expose:
      - "5055"
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions